<?php
/**
 * @file Creates configurable block to add taglines to homepage quicksearch
 */

/**
 * Implements hook_menu().
 */
function search_tagline_menu() {
  $items = array();

  $items['admin/config/user-interface/search-tagline'] = array(
    'title' => 'Search Tagline Config',
    'description' => 'Configure search tagline text and options',
    'page callback' => 'drupal_get_form',
    'page arguments' => 'search_tagline_admin_settings',
    'access arguments' => array('search_tagline admin'),
    'file' => 'search_tagline.admin.inc',
    'type' => MENU_NORMAL_ITEM
  );

  return $items;
}

/**
 * Implements hook_block_info().
 */
function search_tagline_block_info() {
  $block = array();

  $block['search_tagline'] = array(
    'info' => t('Search Tagline')
  );

  return $block;
}

/**
 * Implements hook_block_view().
 */
function search_tagline_block_view($delta = '') {
  $block = array();
  $base_path = drupal_get_path('module', 'search_tagline');

  switch($delta) {
    case 'search_tagline':
      $block['subject'] = '';
      $block['content'] = array(
        '#theme' => 'search_tagline',
        '#attached' => array(
          'css' => $base_path . '/css/search_tagline.css'
        )
      );
      break;
  }

  return $block;
}

/**
 * Implements hook_theme().
 */
function search_tagline_theme() {
  $theme = array();
  $base_path = drupal_get_path('module', 'search_tagline');

  $theme['search_tagline'] = array(
    'renter element' => 'elements',
    'path' => $base_path,
    'template' => 'search_tagline'
  );


  return $theme;
}
